# -*- coding: utf-8 -*-
"""exam06_module_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w96px9j4d_8vwFC1nZLdOvwSv1z2OIrz
"""

import mod


print(mod.add(1,2))
print(mod.sub(1,2))

from mod import add

print(add(1,2))

from mod import add, sub

print(sub(1,2))

#import mod
print(mod.PI)

area_solv = mod.Math()
print(area_solv.solv(2))

print(mod.Math.solv2(4))

import exam05_class_3
cal1 = exam05_class_3.calculator()
print(cal1.add(3, 5))